### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by tripodsan** [tripodsan/spaceport#2]
- [x] animate Lyra
- [x] make belt go arround
- [x] implement dispatch
- [x] count points based on limits
- [x] allocate luggages to flights
- [x] human randomizer
